<?php

?>

<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Title</title>
		<link rel="stylesheet" type="text/css" href="/styles/<? echo style_name; ?>/admin.css" />
</head>
<body>
<div class="container">

<p class="print">
<img src="/styles/<? echo style_name; ?>/img/admin/logo.gif">
</p>

<p class="print">
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel augue. Aenean risus ipsum, vulputate a, suscipit in, consequat at, arcu. Ut tempus, quam in pretium tempus, velit lectus auctor nisi, interdum volutpat massa neque cursus lorem. Fusce rhoncus. Duis feugiat, mauris eget eleifend pulvinar, sem metus facilisis purus, vel fermentum dui tortor in magna. Nam rutrum. Duis semper fermentum pede. Maecenas lacinia. Phasellus rhoncus urna eu leo. Curabitur ipsum mi, auctor a, tincidunt at, fermentum a, ipsum. Sed in orci at turpis feugiat rutrum. Nulla in velit sit amet quam luctus imperdiet. Aliquam erat volutpat. Praesent arcu mauris, congue sit amet, auctor et, commodo eget, dolor. Nulla a orci vel ipsum porttitor porta. 
</p>
 
<p class="print">
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel augue. Aenean risus ipsum, vulputate a, suscipit in, consequat at, arcu. Ut tempus, quam in pretium tempus, velit lectus auctor nisi, interdum volutpat massa neque cursus lorem. Fusce rhoncus. Duis feugiat, mauris eget eleifend pulvinar, sem metus facilisis purus, vel fermentum dui tortor in magna. Nam rutrum. Duis semper fermentum pede. Maecenas lacinia. Phasellus rhoncus urna eu leo. Curabitur ipsum mi, auctor a, tincidunt at, fermentum a, ipsum. Sed in orci at turpis feugiat rutrum. Nulla in velit sit amet quam luctus imperdiet. Aliquam erat volutpat. Praesent arcu mauris, congue sit amet, auctor et, commodo eget, dolor. Nulla a orci vel ipsum porttitor porta.  
</p>

<p class="print_login">
Gebruikersnaam: <? echo $user["uid"]; ?><br />
Wachtwoord:  <? echo $user["password"]; ?><br />
</p>
<p class="print_page">
</p>
</div>

<br />

<div class="container">

<p class="print">
<h1 class="print">Tutorial</h1>
</p>

<p class="print">
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel augue. Aenean risus ipsum, vulputate a, suscipit in, consequat at, arcu. Ut tempus, quam in pretium tempus, velit lectus auctor nisi, interdum volutpat massa neque cursus lorem. Fusce rhoncus. Duis feugiat, mauris eget eleifend pulvinar, sem metus facilisis purus, vel fermentum dui tortor in magna. Nam rutrum. Duis semper fermentum pede. Maecenas lacinia. Phasellus rhoncus urna eu leo. Curabitur ipsum mi, auctor a, tincidunt at, fermentum a, ipsum. Sed in orci at turpis feugiat rutrum. Nulla in velit sit amet quam luctus imperdiet. Aliquam erat volutpat. Praesent arcu mauris, congue sit amet, auctor et, commodo eget, dolor. Nulla a orci vel ipsum porttitor porta. 
<lu>
	<li class="print">Vul de inloggegevens in en klik op inloggen</li>
	<li class="print">Kies daarna voor een groot en scherp beeld of een klein en minderscherp beeld. Wanneer u een “adsl/kabel light” internet abonnement heeft kiest u voor 128- of 256 KB/sec, wanneer u een plus/power/fast abonnement heeft kiest u voor 384 KB/s.</li>
	<li class="print">Na +/- 5 seconden wordt u door gelinkt naar de weergave pagina.</li>
</lu>

</p>

<p class="print">
<h3>Problemen tijdens weergave</h3>
</p>

<p class="print">
<lu>
	<li class="print">Wanneer u geen beeld krijgt kan het zijn dat u een verouderde versie van Windows Media Player gebruikt. Ga naar de site van Microsoft en download en installeer de nieuwste versie van Windows Media Player: http://www.microsoft.com/windows/windowsmedia/download/</li>
	<li class="print">Zorg dat gebruik van Cookies toegestaan is binnen de browser</li>
</lu>.

</p>

<p class="print">
</p>



</div>
</body>
</html>